language: scala
sbt_args: 
   -sbt-version 0.13.1
scala:
   - 2.11.6
   - 2.11.5
script:
  - mkdir output
  - sbt clean
  - sbt update
  - sbt compile
  - sbt test
  - sbt "run parcoord_animation"
  - sbt "run toy_example_test"
  - sbt "run high_density_heatmap"
jdk:
  - oraclejdk7
notifications:
  slack: kaspect:ZDGGbLyDsPguWyRxpcrkpqQa
